sudo: required
language: node_js
os:
  - linux
  - windows
branches:
  only:
  - master
matrix:
  allow_failures:
    - os: windows
  include:
    - language: node_js
      node_js: "8"
    - language: node_js
      node_js: "10"
      if: head_branch IS blank AND branch = master
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
    - lantern-data
    - /home/travis/.rvm/gems/
install:
  # if our e2e tests fail in the future it might be that we are not compatible
  # with the latest puppeteer api so we probably need to run on chromimum
  # @see https://github.com/GoogleChrome/lighthouse/pull/4640/files#r171425004
  - export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
  - yarn
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  # see comment above about puppeteer
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_PATH="$(which google-chrome-stable)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - yarn build-all
script:
  - yarn bundlesize
  - yarn diff:sample-json
  - yarn lint
  - yarn unit:silentcoverage
  - yarn type-check
  - yarn smoke:silentcoverage
  - yarn test-clients
  - yarn test-viewer
  - yarn test-lantern
  - yarn i18n:checks
  # _JAVA_OPTIONS is breaking parsing of `compile-devtools` output. See #3338.
  - unset _JAVA_OPTIONS
  # FIXME(paulirish): re-enable after a roll of LH->CDT
  # - yarn compile-devtools
before_cache:
  # the `yarn compile-devtools` task adds these to node_modules, which slows down caching
  - rm -rf ./node_modules/temp-devtoolsfrontend/
  - rm -rf ./node_modules/temp-devtoolsprotocol/
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  yarn codecov; fi
addons:
  chrome: stable
